version: 2.1

jobs:
  build:
    docker:
      - image: circleci/elixir:1.10
      - image: validator/validator:latest
    environment:
      VNU_SERVER_URL: http://localhost:8888/

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix deps.get
      - run: mix compile --warnings-as-errors --force
      - run: mix format --check-formatted
      - run: mix test