version: 2.1

executors:
  elixir-11:
    docker:
      - image: circleci/elixir:1.11
      - image: validator/validator:latest
    environment:
      VNU_SERVER_URL: http://localhost:8888/

  elixir-10:
    docker:
      - image: circleci/elixir:1.10
      - image: validator/validator:latest
    environment:
      VNU_SERVER_URL: http://localhost:8888/

  elixir-9:
    docker:
      - image: circleci/elixir:1.9
      - image: validator/validator:latest
    environment:
      VNU_SERVER_URL: http://localhost:8888/

  elixir-8:
    docker:
      - image: circleci/elixir:1.8
      - image: validator/validator:latest
    environment:
      VNU_SERVER_URL: http://localhost:8888/

commands:
  test:
    steps:
      - run: mix local.hex --force && mix local.rebar --force
      - run: mix deps.get
      - run: mix compile --warnings-as-errors --force
      - run: mix format --check-formatted
      - run: mix test

  test_with_older_deps:
    steps:
      - run: mix local.hex --force && mix local.rebar --force
      - run: mix deps.get
      - run: mix compile --warnings-as-errors --force
      - run: mix format --check-formatted
      - run: mix test
      - run:
          name: mix deps.get (with older deps)
          command: mix deps.get
          environment:
            - WITH_OLDER_DEPS: true
      - run:
          name: mix test (with older deps)
          command: mix test
          environment:
            - WITH_OLDER_DEPS: true

jobs:
  test-elixir-11:
    executor: elixir-11
    working_directory: ~/repo
    steps:
      - checkout
      - test
      - run: mix coveralls.circle
      - test_with_older_deps

  test-elixir-10:
    executor: elixir-10
    working_directory: ~/repo
    steps:
      - checkout
      - test
      - run: mix coveralls.circle
      - test_with_older_deps

  test-elixir-9:
    executor: elixir-9
    working_directory: ~/repo
    steps:
      - checkout
      - test
      - test_with_older_deps

  test-elixir-8:
    executor: elixir-8
    working_directory: ~/repo
    steps:
      - checkout
      - test
      - test_with_older_deps

workflows:
  version: 2
  test:
    jobs:
      - test-elixir-11
      - test-elixir-10:
          requires:
            - test-elixir-11
      - test-elixir-9:
          requires:
            - test-elixir-11
      - test-elixir-8:
          requires:
            - test-elixir-11
